class LocatorIlx:

    # NAMEs
    ilx_email = 'email'
    ilx_password = 'password'
    group_name = 'name'
    group_path = 'path'
    data = 'group-item'
    confirm = 'confirm'
    int_base_path = 'basePath'
    int_group_path = 'groupPath'

    # XPATHs
    user_email = '//*[@id="root"]/div[2]/div/div/div[2]/ul/div[1]/div[2]'
    group_create = '/html/body/div[2]/div[3]/div/div[2]/form/div[2]/button[2]'
    group_delete = '//*[@id="context-actions-menu"]/div[3]/ul/li[2]/span[1]'
    button_group_del = '/html/body/div[2]/div[3]/div/div[3]/button[2]/span'
    before_button_remove_from_group = '//*[@id="root"]/div[3]/div/div[2]/div/div[2]/div/div/div/div[1]/div[3]/button'
    button_remove_from_group = '//*[@id="context-actions-menu"]/div[3]/ul/li[2]/span[1]'
    remove_from_group = '/html/body/div[2]/div[3]/div/div[2]/div[4]/div/div/input'
    after_button_remove_from_group = '/html/body/div[2]/div[3]/div/div[3]/button[2]'
    access = '//*[@id="sidebar-item-access"]/div[2]'
    access_before = '//*[@id="sidebar-item-0"]/span'
    button_access_key = '//*[@id="root"]/div[3]/div/div[1]/button'
    input_access_key = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div/div/div/input'
    create_access_key = '/html/body/div[2]/div[3]/div/div[2]/form/div[2]/button[2]'
    group_edit = '//*[@id="context-actions-menu"]/div[3]/ul/li[1]/span[1]'
    input_group_edit = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div[1]/div/div/input'
    input_path_edit = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div[2]/div/div/input'
    save_edit_group = '/html/body/div[2]/div[3]/div/div[2]/form/div[2]/button[2]'
    button_create_int = '/html/body/div[2]/div[3]/div/div[2]/form/div[2]/button[2]'
    button_int = '//*[@id="root"]/div[3]/div/div[2]/div/div[2]/div[1]/div/div[2]/div/div'
    button_edit_int = '//*[@id="root"]/div[3]/div/div[2]/button'
    int_name = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div/div/div/input'
    button_int_save = '/html/body/div[2]/div[3]/div/div[2]/form/div[2]/button[2]'
    name_int = '//*[@id="root"]/div[3]/div/div[1]/nav/ol/li[3]/span'
    edit_int = '//*[@id="root"]/div[3]/div/div[2]/div/div[2]/div[1]/div/div[2]/div/div/div[1]/div[3]/button/span[1]'
    add_to_group = '//*[@id="context-actions-menu"]/div[3]/ul/li[1]'
    button_add_int = '/html/body/div[2]/div[3]/div/div[2]/div[2]/button[2]'
    edit_group_first = '//*[@id="root"]/div[3]/div/div[2]/div/div[2]/div[3]/div/div[2]/div/div/div[1]/div[3]/button'
    edit_group_second = '//*[@id="root"]/div[3]/div/div[2]/div/div[2]/div[2]/div/div[2]/div/div/div[1]/div[3]/button'
    move_to_group = '//*[@id="context-actions-menu"]/div[3]/ul/li[1]'
    move_int = '/html/body/div[2]/div[3]/div/div[2]/div[2]/button[2]'
    del_int_from_group = '//*[@id="context-actions-menu"]/div[3]/ul/li[3]'
    confirm_delete_from_group = '/html/body/div[2]/div[3]/div/div[2]/div[3]/div/div/input'
    delete_int_from_group = '/html/body/div[2]/div[3]/div/div[3]/button[2]'
    remove_int_from_group = '//*[@id="context-actions-menu"]/div[3]/ul/li[2]'
    confirm_remove_int = '/html/body/div[2]/div[3]/div/div[2]/div[4]/div/div/input'
    button_remove_int = '/html/body/div[2]/div[3]/div/div[3]/button[2]'
    delete_int_first = '//*[@id="context-actions-menu"]/div[3]/ul/li[2]'
    confirm_delete_int = '/html/body/div[2]/div[3]/div/div[2]/div[3]/div/div/input'
    delete_int_second = '/html/body/div[2]/div[3]/div/div[3]/button[2]'

    connection = '//*[@id="sidebar-item-1"]'
    new_connection = '//*[@id="root"]/div[3]/div/div[1]/button'
    connection_name = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div[1]/div/div/input'
    connection_url = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div[2]/div/div/input'
    connection_save = '/html/body/div[2]/div[3]/div/div[2]/form/div[2]/button[2]'

    connect_type = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div[3]/div/div/div/div/button'
    select_connect = '/html/body/div/div[3]/div/div[3]/div[2]/div/div[2]/div[1]/div/table/tbody/tr/td[2]/div/span'
    get_connect = '/html/body/div/div[3]/div/div[1]/nav/ol/li[1]/a'

    int_template = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div[1]/div/div/div/div/button'
    int_description = '/html/body/div/div[3]/div/div[3]/div[1]/div/div[2]/div/div/table/tbody/tr/td[1]/div'
    int_auth = '/html/body/div/div[3]/div/div[3]/div[1]/div/div/button[2]/span[1]'
    open_chose_key = '/html/body/div/div[3]/div/div[3]/div[3]/div/form/div[1]/div/div/div/div/div/button'
    save_api_key = '/html/body/div/div[3]/div/div[3]/div[3]/div/form/div[2]/button[2]'
    return_to_int = '/html/body/div/div[3]/div/div[1]/nav/ol/li[3]/a'
    chose_connect_type = "//ul[@role='listbox']/li[@role='option']"
    client_id = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div[12]/div/div/input'
    user_name = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div[14]/div/div/input'
    client_secret = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div[13]/div/div/input'
    connect_passwd = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div[15]/div/div/input'
    token_url = '/html/body/div[2]/div[3]/div/div[2]/form/div[1]/div[16]/div/div/input'
    connect_name = '//*[@id="root"]/div[3]/div/div[1]/nav/ol/li[3]'
    connect_chose = '//*[@id="root"]/div[3]/div/div[2]/div[1]/div/div/div[1]/div[3]/button'
    connect_delete = '//*[@id="context-actions-menu"]/div[3]/ul/li[2]'
    chose_connect = '//*[@id="root"]/div[3]/div/div[2]/div/div/div/div[1]/div[1]/span'
    chose_int = '//*[@id="root"]/div[3]/div/div[3]/div[2]/div[2]/div/div/div/div[1]/div/span'
    chose_dest_endpoint = '//*[@id="root"]/div[3]/div/div[3]/div[2]/div/div[2]/div[1]/div/table/tbody/tr/td[2]/div'
    confirm_delete_connect = '/html/body/div[2]/div[3]/div/div[2]/div[3]/div/div/input'
    connect_save = '/html/body/div[2]/div[3]/div/div[3]/button[2]'
    data_connects = '//*[@id="sidebar-item-access"]'
    edit_connect = '/html/body/div[2]/div[3]/ul/li[1]'
    connect_name_text = '/html/body/div/div[3]/div/div[2]/div/div/div/div[1]/div[1]/span'
    access_key_name = '/html/body/div/div[3]/div/div[3]/div/form/div[1]/div[1]/div/div/input'

    # CLASS_NAMEs
    button = 'MuiButton-label'
    chose_group = 'add-to-group-list-container'
    chose_move_group = 'add-to-group-list-container'
    chose_endpoint = '/html/body/div/div[2]/div/div/div[2]/ul/div[2]/span'

    # TAG_NAMEs
    tag_name = 'li'
