version: 0.2

phases:
  build:
    commands:
      - export PATH=$PATH:/usr/bin/chromium-browser
      - export PYTHONPATH=$PYTHONPATH:.
      - pytest -m regression --browser_name=chrome-headless --environment=$ENVIRONMENT --credentials --base_admin_email=$ADMIN_EMAIL --base_admin_password=$ADMIN_PASSWORD --base_distributor_email=$DISTRIBUTOR_EMAIL --base_distributor_password=$DISTRIBUTOR_PASSWORD --base_permission_distributor_email=$PERMISSION_DISTRIBUTOR_EMAIL --base_permission_distributor_password=$PERMISSION_DISTRIBUTOR_PASSWORD --base_customer_email=$CUSTOMER_EMAIL --base_customer_password=$CUSTOMER_PASSWORD --base_checkout_group_email=$CHECKOUT_GROUP_EMAIL --base_checkout_group_password=$CHECKOUT_GROUP_PASSWORD --cognito_user_pool_id=$USER_POOL_ID --cognito_client_id=$CLIENT_ID --cognito_checkout_client_id=$CHECKOUT_CLIENT_ID --cognito_mobile_client_id=$MOBILE_CLIENT_ID --testrail_email=$TESTRAIL_EMAIL --testrail_password=$TESTRAIL_PASSWORD .
