version: 0.2

phases:
  build:
    commands:
      - export PATH=$PATH:/usr/bin/chromium-browser
      - export PYTHONPATH=$PYTHONPATH:.
      - BUCKET_DIR_NAME=${CODEBUILD_BUILD_NUMBER:=latest}
      - LOCAL_DIR_NAME=screenshots
      - mkdir -p $LOCAL_DIR_NAME
      - pytest --browser_name=chrome-headless --environment=prod --smoke_distributor_email=$SMOKE_DISTRIBUTOR_EMAIL --smoke_distributor_password=$SMOKE_DISTRIBUTOR_PASSWORD --smoke_customer_email=$SMOKE_CUSTOMER_EMAIL --smoke_customer_password=$SMOKE_CUSTOMER_PASSWORD --testrail_email=$TESTRAIL_EMAIL --testrail_password=$TESTRAIL_PASSWORD --credentials --screenshot -m smoke .
    finally:
      - aws s3 cp $LOCAL_DIR_NAME s3://$RESULT_BUCKET_NAME/$BUCKET_DIR_NAME --recursive
